### ISSUE TITLE
please update the documentation for this addon 

### ISSUE THREAD

**Issue by RacerXx** [AlwarrenSidh/ArmAToolbox#13]
please update the documentation or have somebody with some knowledge update the documentation for this addon especially for the blender 2.8 version as the UI for blender has changed. Bundle the documentation with the repository and not a 10 year old outdated website that nobody,if they come here to github,even knows about. What good is a addon if nobody knows how to use it?

**Comment by AlwarrenSidh** [comment]
Are you volunteering? :)

**Comment by RacerXx** [comment]
sigh. maybe you not understanding. I cant write the documentation if i dont know how to use it. Thats my point! I mean come on Alwarren you been a member of the community for years now. Can you help us out a little? Isnt the point of this addon to make life a little easier for modders?

**Comment by AlwarrenSidh** [comment]
I am starting to wonder if you are aware of the irony. "Can you help us out a little?", well yeah, glad that you mentioned it. I made a box of tools that allows you to use Blender for making Arma models instead of having to use Object Builder. Does that quality as "help us out a little"?

No, I can't make a video or something and "just go through and tell people what everything is for an how to set it up". For one thing, I lack the time, because this here is only one of the projects I am involved in, I have actual daytime work, and remnants of a life.

Secondly, with the change to 2.80, a lot of the code and UI are in a state of flux and are constantly changing. 

I am trying to be helpful on the forum and on Discord. There are other people on the BIS forum that also answer questions. Am I really asking too much that you invest a tiny bit of time to ask questions?

But you make it sound like I am deliberately making things difficult for people. You can always go and use the Wavefront OBJ exporter and re-import into Object Builder if figuring out this addon is asking too much.

**Comment by RacerXx** [comment]
wow man you are going to take offense to my comments because i came here suggesting documentation? I have no interest in going on BI forums and their condescending attitudes. Obviously you are a part of that little click. So yeah whatever i dont give a damm if you finish it or not. You dont want to support your own work and instead belittle me and make excuses then thats your problem. Go fuck yourself then! I dont need you

**Comment by AlwarrenSidh** [comment]
ROFL that escalated quickly

**Comment by RacerXx** [comment]
dont start none there wont be none. ROFL
