### ISSUE TITLE
About Wrong I/O MDL Version

### ISSUE THREAD

**Issue by yhh1209** [AlwarrenSidh/ArmAToolbox#38]
How to resolve this error? I tried install multiple versions of blender and  all of these can't resolve this error. Or it is an error about p3d file?

**Comment by yhh1209** [comment]
[https://imgtu.com/i/XnxBbq](url)

**Comment by yhh1209** [comment]
[url=https://imgtu.com/i/XnxBbq][img]https://s1.ax1x.com/2022/05/28/XnxBbq.md.png[/img][/url]

**Comment by AlwarrenSidh** [comment]
You are trying to load a binarized file. Blender (or ObjectBuilder) cannot load binarized files. You need to contact the author and ask for an unbinarized file.

**Comment by yhh1209** [comment]
OK, thank you for your reply!

**Comment by Callum0824** [comment]
yes it can you just need the arma3toolbox and it will happily let you import binarized p3ds...

**Comment by AlwarrenSidh** [comment]
It is intentional that the toolbox doesn't support binarized P3D's, because usually if someone wants to share their work they do it as unbinarized files. Binarized files are usually ripped from existing PBO's, and I do not support this, nor do I support telling people how to circumvent it.

Thank you for your understanding.
